# Generated by Django 4.2.3 on 2023-08-04 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0003_maintenance_maintenanceexpense_document'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='maintenanceexpense',
            name='maintenance',
        ),
        migrations.RemoveField(
            model_name='expense',
            name='section',
        ),
        migrations.AddField(
            model_name='maintenance',
            name='total_spent',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='expense',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.DeleteModel(
            name='ExpenseSection',
        ),
        migrations.DeleteModel(
            name='MaintenanceExpense',
        ),
    ]
