# Generated by Django 4.2.3 on 2023-08-04 16:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0004_remove_maintenanceexpense_maintenance_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='maintenance',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='cars.maintenance'),
            preserve_default=False,
        ),
    ]
