# Generated by Django 4.2.3 on 2023-08-22 23:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0011_document_file_alter_document_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maintenance',
            name='car',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='maintenances', to='cars.car'),
        ),
    ]
