# Generated by Django 4.2.3 on 2023-08-22 23:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0012_alter_maintenance_car'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='car',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expenses', to='cars.car'),
        ),
    ]
