# Generated by Django 4.2.3 on 2023-08-23 15:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cars', '0014_alter_car_options_alter_document_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/', verbose_name='Imagen'),
        ),
        migrations.AlterField(
            model_name='car',
            name='model',
            field=models.CharField(max_length=100, verbose_name='Descripcion'),
        ),
        migrations.AlterField(
            model_name='car',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='car',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuario'),
        ),
        migrations.AlterField(
            model_name='car',
            name='variable_type',
            field=models.CharField(choices=[('millas', 'Millas'), ('kilometros', 'Kilómetros')], max_length=10, verbose_name='Tipo de Variable'),
        ),
        migrations.AlterField(
            model_name='car',
            name='year',
            field=models.PositiveIntegerField(verbose_name='Inicio'),
        ),
        migrations.AlterField(
            model_name='document',
            name='car',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cars.car', verbose_name='Carro'),
        ),
        migrations.AlterField(
            model_name='document',
            name='due_date',
            field=models.DateField(verbose_name='Fecha de Mantenimiento'),
        ),
        migrations.AlterField(
            model_name='document',
            name='file',
            field=models.FileField(upload_to='documents/files/', verbose_name='Archivo'),
        ),
        migrations.AlterField(
            model_name='document',
            name='picture',
            field=models.ImageField(upload_to='documents/images/', verbose_name='Imagen'),
        ),
        migrations.AlterField(
            model_name='document',
            name='title',
            field=models.CharField(max_length=100, verbose_name='Fecha'),
        ),
        migrations.AlterField(
            model_name='expense',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='cantidad'),
        ),
        migrations.AlterField(
            model_name='expense',
            name='car',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expenses', to='cars.car', verbose_name='Carro'),
        ),
        migrations.AlterField(
            model_name='expense',
            name='date',
            field=models.DateField(verbose_name='Fecha'),
        ),
        migrations.AlterField(
            model_name='expense',
            name='maintenance',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cars.maintenance', verbose_name='Mantenimiento'),
        ),
        migrations.AlterField(
            model_name='expense',
            name='tag',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cars.expensetag', verbose_name='Etiqueta'),
        ),
        migrations.AlterField(
            model_name='expensetag',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='maintenance',
            name='car',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='maintenances', to='cars.car', verbose_name='Carro'),
        ),
        migrations.AlterField(
            model_name='maintenance',
            name='date',
            field=models.DateField(verbose_name='Fecha'),
        ),
        migrations.AlterField(
            model_name='maintenance',
            name='hour_meter',
            field=models.PositiveIntegerField(verbose_name='Horometro'),
        ),
        migrations.AlterField(
            model_name='maintenance',
            name='mileage_km',
            field=models.PositiveIntegerField(verbose_name='Kilometraje'),
        ),
        migrations.AlterField(
            model_name='maintenance',
            name='total_spent',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Total Gastado'),
        ),
    ]
